
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EatWhatLah' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EatWhatLah
  pod 'SwiftSpinner', '~> 2.2'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'iOSDropDown'
end
